disabled_rules:
  - large_tuple
  - trailing_whitespace
  - todo
  - opening_brace
  - nesting
included:
  - DadJokesNetworking
  - DadJokesUI
  - DadJokes
excluded:
  - Pods
  - .build
  - .derivedData
  - DadJokesUI/DadJokesUITests
  - DadJokesNetworking/DadJokesNetworkingTests
  - DadJokes/DadJokesTests
line_length: 200
file_length:
  warning: 200
  error: 250
identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
    - x
    - y