# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc 'Set up the development environment'
  lane :setup do
    xcodegen
  end
  desc 'Prepares the environment for build / test'
  lane :prepare do
    Dir.chdir("..") do
      if File.file?("project.yml")
        sh("xcodegen", step_name: "Generating project file")
      end
    end
  end

  desc "Testing"
  lane :test do
    scan
    slather
  end
end